# Package: sys/config

syscfg.defs:
    CONFIG_FCB:
        description: 'TBD'
        value: 0
        restrictions:
            - '!CONFIG_NFFS'
            - 'CONFIG_FCB_FLASH_AREA'
    CONFIG_FCB_FLASH_AREA:
        description: 'TBD'
        type: 'flash_owner'
        value:
    CONFIG_FCB_MAGIC:
        description: 'TBD'
        value: 0xc09f6e5e

    CONFIG_NFFS:
        description: 'TBD'
        value: 0
        restrictions:
            - '!CONFIG_FCB'
    CONFIG_NFFS_DIR:
        description: 'TBD'
        value: '"/cfg"'
    CONFIG_NFFS_FILE:
        description: 'TBD'
        value: '"/cfg/run"'
    CONFIG_NFFS_MAX_LINES:
        description: 'TBD'
        value: 32

    CONFIG_NEWTMGR:
        description: 'TBD'
        value: 0

    CONFIG_CLI:
        description: 'TBD'
        value: 0
        restrictions:
            - 'SHELL_TASK'
